// <auto-generated />
using System;
using DataWarehouse.Schema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataWarehouse.Schema.Migrations
{
    [DbContext(typeof(ResearchWarehouseDbContext))]
    [Migration("20260322123240_AddAdjustedPriceBasisUniqueness")]
    partial class AddAdjustedPriceBasisUniqueness
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("DataWarehouse.Schema.Entities.CorporateAction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("ActionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("AdjustmentFactor")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT");

                    b.Property<string>("AttributesJson")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long?>("IngestionRunId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("RelatedProviderSymbol")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("SymbolMasterId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IngestionRunId");

                    b.HasIndex("SymbolMasterId", "ActionDate");

                    b.HasIndex("SymbolMasterId", "ActionDate", "ActionType", "Provider", "Value")
                        .IsUnique();

                    b.ToTable("corporate_actions", (string)null);
                });

            modelBuilder.Entity("DataWarehouse.Schema.Entities.IndexConstituentPit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("IndexCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("SymbolMasterId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Weight")
                        .HasPrecision(12, 8)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SymbolMasterId");

                    b.HasIndex("IndexCode", "EffectiveFrom");

                    b.HasIndex("IndexCode", "SymbolMasterId", "EffectiveFrom")
                        .IsUnique();

                    b.ToTable("index_constituents_pit", null, t =>
                        {
                            t.HasCheckConstraint("CK_index_constituents_pit_effective_range", "EffectiveTo IS NULL OR EffectiveTo >= EffectiveFrom");
                        });
                });

            modelBuilder.Entity("DataWarehouse.Schema.Entities.IngestionRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pipeline")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestParametersJson")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("RowsInserted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RowsRead")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RowsUpdated")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RunId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("Pipeline", "StartedAtUtc");

                    b.ToTable("ingestion_runs", (string)null);
                });

            modelBuilder.Entity("DataWarehouse.Schema.Entities.PriceDailyAdjusted", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AdjustedClose")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<string>("AdjustmentBasis")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AdjustmentFactor")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Close")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("High")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<long?>("IngestionRunId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Low")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Open")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("SymbolMasterId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("TradeDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("Volume")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IngestionRunId");

                    b.HasIndex("SymbolMasterId", "TradeDate");

                    b.HasIndex("SymbolMasterId", "TradeDate", "Provider", "AdjustmentBasis")
                        .IsUnique();

                    b.ToTable("prices_daily_adjusted", null, t =>
                        {
                            t.HasCheckConstraint("CK_prices_daily_adjusted_factor_non_negative", "AdjustmentFactor >= 0");

                            t.HasCheckConstraint("CK_prices_daily_adjusted_positive_volume", "Volume >= 0");

                            t.HasCheckConstraint("CK_prices_daily_adjusted_price_order", "High >= Low AND Open >= Low AND Open <= High AND Close >= Low AND Close <= High AND AdjustedClose >= 0");
                        });
                });

            modelBuilder.Entity("DataWarehouse.Schema.Entities.PriceDailyRaw", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Close")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("High")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<long?>("IngestionRunId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Low")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Open")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("SymbolMasterId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("TradeDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("Volume")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Vwap")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IngestionRunId");

                    b.HasIndex("SymbolMasterId", "TradeDate");

                    b.HasIndex("SymbolMasterId", "TradeDate", "Provider")
                        .IsUnique();

                    b.ToTable("prices_daily_raw", null, t =>
                        {
                            t.HasCheckConstraint("CK_prices_daily_raw_positive_volume", "Volume >= 0");

                            t.HasCheckConstraint("CK_prices_daily_raw_price_order", "High >= Low AND Open >= Low AND Open <= High AND Close >= Low AND Close <= High");
                        });
                });

            modelBuilder.Entity("DataWarehouse.Schema.Entities.QaResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AffectedRows")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CheckName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailsJson")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<long?>("IngestionRunId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IngestionRunId");

                    b.HasIndex("Severity", "Status", "CreatedUtc");

                    b.ToTable("qa_results", (string)null);
                });

            modelBuilder.Entity("DataWarehouse.Schema.Entities.SymbolMapping", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderSymbol")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("SymbolMasterId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SymbolMasterId", "EffectiveFrom");

                    b.HasIndex("Provider", "ProviderSymbol", "EffectiveFrom")
                        .IsUnique();

                    b.ToTable("symbol_mapping", null, t =>
                        {
                            t.HasCheckConstraint("CK_symbol_mapping_effective_range", "EffectiveTo IS NULL OR EffectiveTo >= EffectiveFrom");
                        });
                });

            modelBuilder.Entity("DataWarehouse.Schema.Entities.SymbolMaster", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DelistedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExchangeMic")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("ListedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("symbol_master", (string)null);
                });

            modelBuilder.Entity("DataWarehouse.Schema.Entities.CorporateAction", b =>
                {
                    b.HasOne("DataWarehouse.Schema.Entities.IngestionRun", "IngestionRun")
                        .WithMany("CorporateActions")
                        .HasForeignKey("IngestionRunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DataWarehouse.Schema.Entities.SymbolMaster", "SymbolMaster")
                        .WithMany("CorporateActions")
                        .HasForeignKey("SymbolMasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IngestionRun");

                    b.Navigation("SymbolMaster");
                });

            modelBuilder.Entity("DataWarehouse.Schema.Entities.IndexConstituentPit", b =>
                {
                    b.HasOne("DataWarehouse.Schema.Entities.SymbolMaster", "SymbolMaster")
                        .WithMany("IndexConstituents")
                        .HasForeignKey("SymbolMasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SymbolMaster");
                });

            modelBuilder.Entity("DataWarehouse.Schema.Entities.PriceDailyAdjusted", b =>
                {
                    b.HasOne("DataWarehouse.Schema.Entities.IngestionRun", "IngestionRun")
                        .WithMany("AdjustedPrices")
                        .HasForeignKey("IngestionRunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DataWarehouse.Schema.Entities.SymbolMaster", "SymbolMaster")
                        .WithMany("AdjustedPrices")
                        .HasForeignKey("SymbolMasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IngestionRun");

                    b.Navigation("SymbolMaster");
                });

            modelBuilder.Entity("DataWarehouse.Schema.Entities.PriceDailyRaw", b =>
                {
                    b.HasOne("DataWarehouse.Schema.Entities.IngestionRun", "IngestionRun")
                        .WithMany("RawPrices")
                        .HasForeignKey("IngestionRunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DataWarehouse.Schema.Entities.SymbolMaster", "SymbolMaster")
                        .WithMany("RawPrices")
                        .HasForeignKey("SymbolMasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IngestionRun");

                    b.Navigation("SymbolMaster");
                });

            modelBuilder.Entity("DataWarehouse.Schema.Entities.QaResult", b =>
                {
                    b.HasOne("DataWarehouse.Schema.Entities.IngestionRun", "IngestionRun")
                        .WithMany("QaResults")
                        .HasForeignKey("IngestionRunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("IngestionRun");
                });

            modelBuilder.Entity("DataWarehouse.Schema.Entities.SymbolMapping", b =>
                {
                    b.HasOne("DataWarehouse.Schema.Entities.SymbolMaster", "SymbolMaster")
                        .WithMany("SymbolMappings")
                        .HasForeignKey("SymbolMasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SymbolMaster");
                });

            modelBuilder.Entity("DataWarehouse.Schema.Entities.IngestionRun", b =>
                {
                    b.Navigation("AdjustedPrices");

                    b.Navigation("CorporateActions");

                    b.Navigation("QaResults");

                    b.Navigation("RawPrices");
                });

            modelBuilder.Entity("DataWarehouse.Schema.Entities.SymbolMaster", b =>
                {
                    b.Navigation("AdjustedPrices");

                    b.Navigation("CorporateActions");

                    b.Navigation("IndexConstituents");

                    b.Navigation("RawPrices");

                    b.Navigation("SymbolMappings");
                });
#pragma warning restore 612, 618
        }
    }
}
